version: "3"
services:
  nginx:
    image: kitspace/nginx-certbot-plugin
    restart: unless-stopped 
    environment:
      - RUN_CERTBOT=true
      - CERTBOT_DOMAINS=outright.blog,www.outright.blog
      - CERTBOT_EMAIL=outright@freshworks.com
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nuxt
      - wp
    networks:
      - flat-network
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
  nuxt:
    build: ./nuxt
    depends_on:
      - wp
      - db
    networks:
      - flat-network
    restart: always
    command: "npm run dev"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
    networks:
      - flat-network
  wp:
    build: ./wordpress
    volumes:
      - ./wordpress/plugins:/app/wordpress/wp-content/plugins
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - flat-network
  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: somewordpress
    networks:
      - flat-network

networks:
  flat-network:

volumes:
  db_data:
  nginx_secrets:

